# Generated by Django 5.2.5 on 2025-09-04 18:20

import bookmarks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0048_userprofile_default_mark_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="ollama_base_api_url",
            field=models.CharField(
                blank=True,
                default=bookmarks.models.get_ollama_base_api_url,
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="ollama_model_name",
            field=models.CharField(
                blank=True,
                default=bookmarks.models.get_ollama_model_name,
                max_length=100,
            ),
        ),
    ]
